# QUESTION SET OF THE PYTHON PROGRAMMING LANGUAGE

 #python: [
    # {q:'What is the output? print(type([]))', o:['<class "list">','<type "list">','list','array'], a:0, e:'type([]) returns the list type.'},
    #     {q:'Which keyword is used to define a function?', o:['fun','def','function','lambda'], a:1, e:'def is used to define a function.'},
    #     {q:'What does len("Code") return?', o:['3','4','5','Error'], a:1, e:'len() counts characters in the string.'},
    #     {q:'Which of these is immutable?', o:['list','dict','set','tuple'], a:3, e:'Tuples cannot be changed after creation.'},
    #     {q:'What is the result of 2 ** 3 ?', o:['6','8','9','5'], a:1, e:'** means exponentiation.'},
    #     {q:'Which method adds an item to a list?', o:['append()','add()','push()','insertItem()'], a:0, e:'append() adds one element to the end of a list.'},
    #     {q:'What is a correct way to create a set?', o:['{}','set()','[]','()'], a:1, e:'set() creates an empty set.'},
    #     {q:'What symbol starts a comment in Python?', o:['//','#','/*','--'], a:1, e:'# is used for comments in Python.'},
    #     {q:'What does range(5) produce?', o:['1 to 5','0 to 4','0 to 5','5 numbers starting from 1'], a:1, e:'range(5) starts from 0 and ends at 4.'},
    #     {q:'Which is a valid variable name?', o:['2name','my-name','my_name','my name'], a:2, e:'Underscores are valid in variable names.'},
    #     {q:'What is the output? print(10 // 3)', o:['3.33','3','4','2'], a:1, e:'// performs floor division.'},
    #     {q:'Which data type stores key-value pairs?', o:['list','tuple','dict','set'], a:2, e:'Dictionaries store key-value pairs.'},
    #     {q:'What keyword is used for looping over a sequence?', o:['loop','for','iterate','repeat'], a:1, e:'for is the standard loop keyword.'},
    #     {q:'What is the output? print(bool(0))', o:['True','False','0','Error'], a:1, e:'0 is falsy, so bool(0) is False.'},
    #     {q:'Which module is used for random numbers?', o:['random','math','os','sys'], a:0, e:'random provides random functions.'},
    #     {q:'What is the output? print("Hi"*3)', o:['HiHiHi','Hi3','Error','3Hi'], a:0, e:'Strings can be repeated with *.'},
    #     {q:'Which one is a Python tuple?', o:['[1,2]','{1,2}','(1,2)','<1,2>'], a:2, e:'Tuples use parentheses.'},
    #     {q:'How do you import a module named math?', o:['include math','import math','using math','require math'], a:1, e:'import math is correct.'},
    #     {q:'What is the output? print(5 == 5.0)', o:['True','False','Error','None'], a:0, e:'Numeric equality compares values.'},
    #     {q:'Which statement handles exceptions?', o:['catch','try/except','error/handle','fix/except'], a:1, e:'try/except is used for exception handling.'},
    #   ],