// QUESTION SET OF THE JAVA PROGRAMMING LANGUAGE

//  java: [
//         {q:'Which method is the entry point in Java?', o:['start()','main()','run()','init()'], a:1, e:'main() is the entry point.'},
//         {q:'Which package is imported by default?', o:['java.util','java.lang','java.io','none'], a:1, e:'java.lang is imported automatically.'},
//         {q:'Which keyword creates an object?', o:['new','class','this','void'], a:0, e:'new creates objects.'},
//         {q:'What is the size of int in Java?', o:['8-bit','16-bit','32-bit','64-bit'], a:2, e:'int is 32-bit.'},
//         {q:'Which is not a Java access modifier?', o:['public','private','protected','package'], a:3, e:'package is not a keyword access modifier.'},
//         {q:'What does JVM stand for?', o:['Java Variable Machine','Java Virtual Machine','Joint Virtual Module','Java Verified Method'], a:1, e:'JVM means Java Virtual Machine.'},
//         {q:'Which collection does not allow duplicates?', o:['List','Queue','Set','ArrayList'], a:2, e:'Set does not allow duplicate elements.'},
//         {q:'Which keyword is used to inherit a class?', o:['implements','extends','inherits','super'], a:1, e:'extends is used for class inheritance.'},
//         {q:'What is String in Java?', o:['Primitive type','Class','Interface','Method'], a:1, e:'String is a class.'},
//         {q:'Which loop is best when iterations are known?', o:['for','do-while','while','foreach only'], a:0, e:'for loop is ideal for known iterations.'},
//         {q:'Which is used for exceptions?', o:['try/catch','if/else','switch','break'], a:0, e:'try/catch handles exceptions.'},
//         {q:'Can a Java class extend multiple classes?', o:['Yes','No','Only abstract classes','Only interfaces'], a:1, e:'Java does not support multiple class inheritance.'},
//         {q:'What does == compare for objects?', o:['Content','Reference','Length','Hash only'], a:1, e:'== compares references for objects.'},
//         {q:'Which is a non-primitive type?', o:['int','double','boolean','String'], a:3, e:'String is a reference type.'},
//         {q:'What is autoboxing?', o:['Convert object to primitive','Convert primitive to object','Compile code','Run code'], a:1, e:'Autoboxing converts primitive to wrapper objects.'},
//         {q:'What is the output of System.out.println(5/2); ?', o:['2.5','2','3','Error'], a:1, e:'Integer division returns 2.'},
//         {q:'Which keyword prevents overriding?', o:['static','final','private','abstract'], a:1, e:'final prevents method overriding.'},
//         {q:'Which interface is used for sorting collections?', o:['Comparable','Runnable','Serializable','Cloneable'], a:0, e:'Comparable defines natural ordering.'},
//         {q:'What does super refer to?', o:['Current object','Parent class','Static block','Package'], a:1, e:'super refers to the parent class.'},
//         {q:'Which statement exits a loop?', o:['stop','exit','break','leave'], a:2, e:'break exits a loop.'},
//       ],