// QUESTION SET OF THE C++ PROGRAMMING LANGUAGE

//  cpp: [
//         {q:'Which header is commonly used for input/output?', o:['stdio.h','iostream','stdlib','conio.h'], a:1, e:'iostream is used for C++ streams.'},
//         {q:'Which operator is used to access members via pointer?', o:['.','->','::','*'], a:1, e:'-> is used with pointers to access members.'},
//         {q:'What is the output? cout << 5/2;', o:['2.5','2','3','Error'], a:1, e:'Integer division gives 2.'},
//         {q:'Which is used to define a class?', o:['struct','class','object','template'], a:1, e:'class defines a class.'},
//         {q:'What does STL stand for?', o:['Standard Template Library','System Template Loop','Standard Type Link','Simple Template List'], a:0, e:'STL means Standard Template Library.'},
//         {q:'Which container stores unique ordered keys?', o:['vector','set','list','stack'], a:1, e:'set stores unique ordered keys.'},
//         {q:'Which keyword is used for constant variables?', o:['const','final','static','immutable'], a:0, e:'const marks constant variables.'},
//         {q:'Which operator allocates memory?', o:['malloc','new','alloc','create'], a:1, e:'new allocates memory in C++.'},
//         {q:'Which is a valid C++ comment?', o:['// comment','<!-- comment -->','# comment','** comment **'], a:0, e:'// is a valid single-line comment.'},
//         {q:'What is function overloading?', o:['Same name, different params','Same name, same params','Different name, same params','None'], a:0, e:'Same function name with different parameters.'},
//         {q:'Which keyword is used for inheritance?', o:['inherits','extends',':','super'], a:2, e:': is used in class inheritance syntax.'},
//         {q:'What is the size of bool?', o:['1 byte','2 bytes','4 bytes','Depends, but usually 1 byte'], a:3, e:'bool size can vary, usually 1 byte.'},
//         {q:'Which loop checks condition first?', o:['do-while','while','repeat-until','for each'], a:1, e:'while checks the condition before each iteration.'},
//         {q:'Which is not a C++ access specifier?', o:['public','private','protected','global'], a:3, e:'global is not an access specifier.'},
//         {q:'What is the output? cout << (2==2);', o:['0','1','true','false'], a:1, e:'true prints as 1 by default.'},
//         {q:'Which keyword defines a namespace?', o:['namespace','space','using','scope'], a:0, e:'namespace defines a namespace.'},
//         {q:'Which is used for dynamic arrays?', o:['vector','map','set','queue'], a:0, e:'vector is commonly used for dynamic arrays.'},
//         {q:'What does nullptr mean?', o:['Zero','Null pointer','Undefined','Invalid'], a:1, e:'nullptr represents a null pointer.'},
//         {q:'Which is used to sort a vector?', o:['sort()','order()','rank()','arrange()'], a:0, e:'sort() sorts a vector.'},
//         {q:'What is polymorphism?', o:['Many forms','One form','No forms','Memory management'], a:0, e:'Polymorphism means many forms.'},
//       ],
  